# Site başlığı
title: Tevarih Veri Tabanı

# Kısa açıklama
tagline: Osmanlı Tarih Eserleri Veri Tabanı

# Repo bilgisi (BU İKİSİ ÇOK ÖNEMLİ)
url: https://dbb-m.github.io
baseurl: /tevarih

# Koleksiyon ayarları
metadata: babinger_cb
